---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: v1.0.0
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-ssh-config.git
  version: v1.0.0
  name: ekara.ssh

- src: https://github.com/ekara-platform/ansible-role-filesystem.git
  version: v1.0.0
  name: ekara.filesystem

- src: https://github.com/ekara-platform/ansible-ebs-automatic-nvme-mapping.git
  version: master
  name: ekara.nvme
