---
- hosts: localhost
  gather_facts: false
  pre_tasks:
  - name: Checkout roles
    command: ansible-galaxy install -r requirements.yaml

  tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration

  - name: Ensure SSH is configured on the Ansible controller to access nodes
    include_role:
      name: ekara.ssh
    vars:
      ek_ssh_proxy: "{{ lookup('env', 'http_proxy') }}"
      ek_ssh_key: "{{ ek_config.ssh.private_key }}"
      ek_ssh_host: '*.azure.com'
      ek_ssh_user: 'ubuntu' # TODO: make this configurable and/or inspect the image to determine OS

  - name: Install AWS modules with PIP
    become: true
    pip:
      state: present
      name:
      - azure==4.0.0
      - packaging=19.2
