---
- name: Define defaults and mandatory settings for the resource group
  set_fact:
    ek_az_rg_defaults: >
      {{
        {
          'name': 'ek_{{ ek_config.environment.id }}',
          'location': '{{ ek_config.params.region }}'
        }
      }}
    ek_az_rg_mandatory: >
      {{
        {
          'state': 'present',
          'tags': {
            'ek_env_id': '{{ ek_config.environment.id }}'
          }
        }
      }}
- name: Combine resource group user settings with default and mandatory settings
  set_fact:
    ek_az_rg_settings: "{{ ek_az_rg_defaults | combine(ek_config.params.resourceGroup | default({}), recursive=True) | combine(ek_az_rg_mandatory, recursive=True) }}"
- debug:
    verbosity: 1
    var: ek_az_rg_settings
- name: Ensure the resource group is present
  azure_rm_resourcegroup: "{{ ek_az_rg_settings }}"
  register: ek_az_rg_info
- debug:
    verbosity: 1
    var: ek_az_rg_info
